### PR TITLE
Upgrade to hybrid component

### LINKED ISSUE #27: iron-swipeable-container doesn't work on polymer 2.0 or hybrid projects
### Description
`iron-swipeable-container` doesn't show the slotted content using polymer 2.0.

### Expected outcome
`iron-swipeable-container` should show the slotted content

### Actual outcome
Don't displays the slotted content.

### Live Demo
Standard demo included in the element: https://github.com/PolymerElements/iron-swipeable-container/blob/master/demo/index.html

#### Option 1:
1. Update standard demo to Polymer 2.0
2. Run polymer serve
3. Try to swipe an element
#### Option 2:
1. Include `iron-swipeable-container` in a Polymer 2 project
2. Try to swipe an element

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

### PR DESCRIPTION
**Pull request by ernysans**
Fixes #27

### CODE REVIEW

**Comment by ernysans** [comment]
I signed it!

**Comment by ernysans** [comment]
I manually verify and the component works now but I wasn't able to fix the test.

**Comment by cdata** [comment]
Is this materially different from #26?

**Comment by ernysans** [comment]
@cdata That PR is incomplete. Please check out that the test are not consider in that one. That is why they pass.

**Pull request closed without merging**
