### PR TITLE
Automatic cleanup!

### PR DESCRIPTION
**Pull request by e111077**

### CODE REVIEW

**Comment by bicknellr** [comment]
The diff after updating the types seems to be getting caught on changes to `package-lock.json`.

**Comment by e111077** [comment]
nice catch!

**Comment by bicknellr** [comment]
Hmm, didn't work...

**Comment by e111077** [comment]
try running format and types and see if it generates a diff? (they shouldn't though)

**Comment by bicknellr** [comment]
(rolled back)
Ok, I'll give that a shot.

**Comment by bicknellr** [comment]
So, this repo did need to be formatted; I'll be a little surprised if it doesn't fail for the same `package-lock.json` diff reason again though.

**Comment by bicknellr** [comment]
Fixed the `package-lock.json` thing thanks to a tip from @keanulee, now it's actually running the tests which seem to be failing on the 1.x variant. They fail locally too, so I restarted the latest master build to see if something changed since the last time it built.

**Comment by bicknellr** [comment]
Oh, just realized that's not going to be useful because master is using node 10...

**Comment by aomarks** [comment]
```
chrome 67 [1.x]          ✖ test/basic.html » native elements » dragging more than halfway swipes it
  timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
chrome 67 [1.x]          ✖ test/basic.html » custom elements » dragging more than halfway swipes it
  timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
chrome 67 [1.x]          ✖ test/basic.html » nested swipe » dragging an element nested in two containers does not swipe both
  timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

Restarting the Travis builds.

**Comment by e111077** [comment]
These test failures might be due to tests failing and not travis in particular

**Pull request merged**
